// Code generated by stanc v2.33.1
#include <stan/model/model_header.hpp>
namespace conjugate_model_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 55> locations_array__ =
  {" (found before start of program)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 22, column 4 to column 30)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 23, column 4 to column 22)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 24, column 4 to column 30)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 25, column 4 to column 25)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 26, column 4 to column 25)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 27, column 4 to column 18)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 28, column 4 to column 32)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 32, column 3 to column 22)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 33, column 3 to column 20)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 60, column 3 to column 21)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 36, column 4 to column 34)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 37, column 4 to column 51)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 35, column 18 to line 38, column 4)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 35, column 3 to line 38, column 4)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 62, column 8 to column 64)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 61, column 18 to line 63, column 1)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 61, column 4 to line 63, column 1)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 43, column 4 to column 39)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 46, column 4 to column 35)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 48, column 8 to column 93)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 47, column 19 to line 49, column 5)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 47, column 4 to line 49, column 5)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 50, column 4 to column 32)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 53, column 4 to column 40)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 54, column 4 to column 40)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 55, column 4 to column 74)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 56, column 4 to column 43)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 3, column 4 to column 20)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 4, column 4 to column 20)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 5, column 4 to column 20)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 6, column 10 to column 11)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 6, column 4 to column 20)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 7, column 11 to column 12)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 7, column 14 to column 15)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 7, column 4 to column 19)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 8, column 10 to column 11)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 8, column 4 to column 34)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 11, column 4 to column 21)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 12, column 4 to column 27)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 13, column 4 to column 27)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 14, column 4 to column 27)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 15, column 4 to column 27)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 16, column 4 to column 22)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 17, column 4 to column 28)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 18, column 4 to column 28)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 22, column 22 to column 23)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 23, column 11 to column 12)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 23, column 14 to column 15)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 24, column 22 to column 23)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 27, column 12 to column 13)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 28, column 22 to column 23)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 32, column 10 to column 11)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 33, column 10 to column 11)",
  " (in 'C:/Users/zacos/Desktop/cyclones/code/conjugate_model.stan', line 60, column 10 to column 11)"};
class conjugate_model_model final : public model_base_crtp<conjugate_model_model> {
 private:
  int N;
  int B;
  int D;
  std::vector<double> W;
  Eigen::Matrix<double,-1,-1> X_data__;
  std::vector<int> basins;
  double a;
  double y_alpha;
  double z_alpha;
  double y_gamma;
  double z_gamma;
  double v2;
  double y_lambda;
  double z_lambda;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
 public:
  ~conjugate_model_model() {}
  conjugate_model_model(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "conjugate_model_model_namespace::conjugate_model_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 28;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 28;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 29;
      context__.validate_dims("data initialization", "B", "int",
        std::vector<size_t>{});
      B = std::numeric_limits<int>::min();
      current_statement__ = 29;
      B = context__.vals_i("B")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "B", B, 1);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "D", "int",
        std::vector<size_t>{});
      D = std::numeric_limits<int>::min();
      current_statement__ = 30;
      D = context__.vals_i("D")[(1 - 1)];
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "D", D, 1);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("W", "N", N);
      current_statement__ = 32;
      context__.validate_dims("data initialization", "W", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      W = std::vector<double>(N, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 32;
      W = context__.vals_r("W");
      current_statement__ = 33;
      stan::math::validate_non_negative_index("X", "N", N);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("X", "D", D);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(D)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(N, D,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), N, D);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 35;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 36;
      stan::math::validate_non_negative_index("basins", "N", N);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "basins", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      basins = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 37;
      basins = context__.vals_i("basins");
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "basins", basins, 0);
      current_statement__ = 38;
      context__.validate_dims("data initialization", "a", "double",
        std::vector<size_t>{});
      a = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 38;
      a = context__.vals_r("a")[(1 - 1)];
      current_statement__ = 38;
      stan::math::check_greater_or_equal(function__, "a", a, 0);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "y_alpha", "double",
        std::vector<size_t>{});
      y_alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 39;
      y_alpha = context__.vals_r("y_alpha")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "y_alpha", y_alpha, 0);
      current_statement__ = 40;
      context__.validate_dims("data initialization", "z_alpha", "double",
        std::vector<size_t>{});
      z_alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 40;
      z_alpha = context__.vals_r("z_alpha")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "z_alpha", z_alpha, 0);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "y_gamma", "double",
        std::vector<size_t>{});
      y_gamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 41;
      y_gamma = context__.vals_r("y_gamma")[(1 - 1)];
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "y_gamma", y_gamma, 0);
      current_statement__ = 42;
      context__.validate_dims("data initialization", "z_gamma", "double",
        std::vector<size_t>{});
      z_gamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 42;
      z_gamma = context__.vals_r("z_gamma")[(1 - 1)];
      current_statement__ = 42;
      stan::math::check_greater_or_equal(function__, "z_gamma", z_gamma, 0);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "v2", "double",
        std::vector<size_t>{});
      v2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 43;
      v2 = context__.vals_r("v2")[(1 - 1)];
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "v2", v2, 0);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "y_lambda", "double",
        std::vector<size_t>{});
      y_lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 44;
      y_lambda = context__.vals_r("y_lambda")[(1 - 1)];
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "y_lambda", y_lambda, 0);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "z_lambda", "double",
        std::vector<size_t>{});
      z_lambda = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 45;
      z_lambda = context__.vals_r("z_lambda")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "z_lambda", z_lambda, 0);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("sig2", "B", B);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("Beta", "B", B);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("Beta", "D", D);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("tau2", "D", D);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("nu", "D", D);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("lambda", "D", D);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("all_sig2", "N", N);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("all_mu", "N", N);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = B + (B * D) + D + 1 + 1 + D + D;
  }
  inline std::string model_name() const final {
    return "conjugate_model_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.33.1",
             "stancflags = "};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "conjugate_model_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> sig2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(B, DUMMY_VAR__);
      current_statement__ = 1;
      sig2 = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, B);
      Eigen::Matrix<local_scalar_t__,-1,-1> Beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(B, D, DUMMY_VAR__);
      current_statement__ = 2;
      Beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(B, D);
      Eigen::Matrix<local_scalar_t__,-1,1> tau2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 3;
      tau2 = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, D);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 4;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 5;
      gamma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 6;
      nu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(D);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 7;
      lambda = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 D);
      Eigen::Matrix<local_scalar_t__,-1,1> all_sig2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> all_mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 14;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 11;
        stan::model::assign(all_sig2,
          stan::model::rvalue(sig2, "sig2",
            stan::model::index_uni(
              stan::model::rvalue(basins, "basins", stan::model::index_uni(i)))),
          "assigning variable all_sig2", stan::model::index_uni(i));
        current_statement__ = 12;
        stan::model::assign(all_mu,
          stan::math::dot_product(
            stan::model::rvalue(X, "X", stan::model::index_uni(i)),
            stan::model::rvalue(Beta, "Beta",
              stan::model::index_uni(
                stan::model::rvalue(basins, "basins",
                  stan::model::index_uni(i))))), "assigning variable all_mu",
          stan::model::index_uni(i));
      }
      {
        current_statement__ = 18;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(W, all_mu,
                         stan::math::sqrt(all_sig2)));
        current_statement__ = 19;
        lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(sig2, alpha,
                         gamma));
        current_statement__ = 22;
        for (int d = 1; d <= D; ++d) {
          current_statement__ = 20;
          lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(
                           stan::model::rvalue(Beta, "Beta",
                             stan::model::index_omni(),
                             stan::model::index_uni(d)),
                           stan::math::rep_vector(
                             stan::model::rvalue(nu, "nu",
                               stan::model::index_uni(d)), B),
                           stan::math::diag_matrix(
                             stan::math::rep_vector(
                               stan::model::rvalue(tau2, "tau2",
                                 stan::model::index_uni(d)), B))));
        }
        current_statement__ = 23;
        lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(tau2, a, lambda));
        current_statement__ = 24;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, y_alpha, (1.0
                         / z_alpha)));
        current_statement__ = 25;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(gamma, y_gamma, (1.0
                         / z_gamma)));
        current_statement__ = 26;
        lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(nu,
                         stan::math::rep_vector(0.0, D),
                         stan::math::diag_matrix(
                           stan::math::rep_vector(v2, D))));
        current_statement__ = 27;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(lambda, y_lambda,
                         (1.0 / z_lambda)));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "conjugate_model_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> sig2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(B, DUMMY_VAR__);
      current_statement__ = 1;
      sig2 = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, B);
      Eigen::Matrix<local_scalar_t__,-1,-1> Beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(B, D, DUMMY_VAR__);
      current_statement__ = 2;
      Beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(B, D);
      Eigen::Matrix<local_scalar_t__,-1,1> tau2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 3;
      tau2 = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, D);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 4;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 5;
      gamma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 6;
      nu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(D);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 7;
      lambda = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 D);
      Eigen::Matrix<local_scalar_t__,-1,1> all_sig2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> all_mu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 14;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 11;
        stan::model::assign(all_sig2,
          stan::model::rvalue(sig2, "sig2",
            stan::model::index_uni(
              stan::model::rvalue(basins, "basins", stan::model::index_uni(i)))),
          "assigning variable all_sig2", stan::model::index_uni(i));
        current_statement__ = 12;
        stan::model::assign(all_mu,
          stan::math::dot_product(
            stan::model::rvalue(X, "X", stan::model::index_uni(i)),
            stan::model::rvalue(Beta, "Beta",
              stan::model::index_uni(
                stan::model::rvalue(basins, "basins",
                  stan::model::index_uni(i))))), "assigning variable all_mu",
          stan::model::index_uni(i));
      }
      {
        current_statement__ = 18;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(W, all_mu,
                         stan::math::sqrt(all_sig2)));
        current_statement__ = 19;
        lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(sig2, alpha,
                         gamma));
        current_statement__ = 22;
        for (int d = 1; d <= D; ++d) {
          current_statement__ = 20;
          lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(
                           stan::model::rvalue(Beta, "Beta",
                             stan::model::index_omni(),
                             stan::model::index_uni(d)),
                           stan::math::rep_vector(
                             stan::model::rvalue(nu, "nu",
                               stan::model::index_uni(d)), B),
                           stan::math::diag_matrix(
                             stan::math::rep_vector(
                               stan::model::rvalue(tau2, "tau2",
                                 stan::model::index_uni(d)), B))));
        }
        current_statement__ = 23;
        lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(tau2, a, lambda));
        current_statement__ = 24;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(alpha, y_alpha, (1.0
                         / z_alpha)));
        current_statement__ = 25;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(gamma, y_gamma, (1.0
                         / z_gamma)));
        current_statement__ = 26;
        lp_accum__.add(stan::math::multi_normal_lpdf<propto__>(nu,
                         stan::math::rep_vector(0.0, D),
                         stan::math::diag_matrix(
                           stan::math::rep_vector(v2, D))));
        current_statement__ = 27;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(lambda, y_lambda,
                         (1.0 / z_lambda)));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "conjugate_model_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> sig2 =
        Eigen::Matrix<double,-1,1>::Constant(B,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      sig2 = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, B);
      Eigen::Matrix<double,-1,-1> Beta =
        Eigen::Matrix<double,-1,-1>::Constant(B, D,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      Beta = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(B, D);
      Eigen::Matrix<double,-1,1> tau2 =
        Eigen::Matrix<double,-1,1>::Constant(D,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      tau2 = in__.template read_constrain_lb<
               Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, D);
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      alpha = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double gamma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      gamma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> nu =
        Eigen::Matrix<double,-1,1>::Constant(D,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 6;
      nu = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(D);
      Eigen::Matrix<double,-1,1> lambda =
        Eigen::Matrix<double,-1,1>::Constant(D,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 7;
      lambda = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 D);
      Eigen::Matrix<double,-1,1> all_sig2 =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> all_mu =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(sig2);
      out__.write(Beta);
      out__.write(tau2);
      out__.write(alpha);
      out__.write(gamma);
      out__.write(nu);
      out__.write(lambda);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 14;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 11;
        stan::model::assign(all_sig2,
          stan::model::rvalue(sig2, "sig2",
            stan::model::index_uni(
              stan::model::rvalue(basins, "basins", stan::model::index_uni(i)))),
          "assigning variable all_sig2", stan::model::index_uni(i));
        current_statement__ = 12;
        stan::model::assign(all_mu,
          stan::math::dot_product(
            stan::model::rvalue(X, "X", stan::model::index_uni(i)),
            stan::model::rvalue(Beta, "Beta",
              stan::model::index_uni(
                stan::model::rvalue(basins, "basins",
                  stan::model::index_uni(i))))), "assigning variable all_mu",
          stan::model::index_uni(i));
      }
      if (emit_transformed_parameters__) {
        out__.write(all_sig2);
        out__.write(all_mu);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 17;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 15;
        stan::model::assign(log_lik,
          stan::math::normal_lpdf<false>(
            stan::model::rvalue(W, "W", stan::model::index_uni(i)), all_mu,
            stan::math::sqrt(all_sig2)), "assigning variable log_lik",
          stan::model::index_uni(i));
      }
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> sig2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(B, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(sig2,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(B),
        "assigning variable sig2");
      out__.write_free_lb(0, sig2);
      Eigen::Matrix<local_scalar_t__,-1,-1> Beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(B, D, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(Beta,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(B, D),
        "assigning variable Beta");
      out__.write(Beta);
      Eigen::Matrix<local_scalar_t__,-1,1> tau2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(tau2,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(D),
        "assigning variable tau2");
      out__.write_free_lb(0, tau2);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 4;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 5;
      gamma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, gamma);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 6;
      stan::model::assign(nu,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(D),
        "assigning variable nu");
      out__.write(nu);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(lambda,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(D),
        "assigning variable lambda");
      out__.write_free_lb(0, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "sig2", "double",
        std::vector<size_t>{static_cast<size_t>(B)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "Beta", "double",
        std::vector<size_t>{static_cast<size_t>(B), static_cast<size_t>(D)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "tau2", "double",
        std::vector<size_t>{static_cast<size_t>(D)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "alpha", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "gamma", "double",
        std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization", "nu", "double",
        std::vector<size_t>{static_cast<size_t>(D)});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "lambda", "double",
        std::vector<size_t>{static_cast<size_t>(D)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> sig2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(B, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sig2_flat__;
        current_statement__ = 1;
        sig2_flat__ = context__.vals_r("sig2");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= B; ++sym1__) {
          stan::model::assign(sig2, sig2_flat__[(pos__ - 1)],
            "assigning variable sig2", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sig2);
      Eigen::Matrix<local_scalar_t__,-1,-1> Beta =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(B, D, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> Beta_flat__;
        current_statement__ = 2;
        Beta_flat__ = context__.vals_r("Beta");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= B; ++sym2__) {
            stan::model::assign(Beta, Beta_flat__[(pos__ - 1)],
              "assigning variable Beta", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(Beta);
      Eigen::Matrix<local_scalar_t__,-1,1> tau2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> tau2_flat__;
        current_statement__ = 3;
        tau2_flat__ = context__.vals_r("tau2");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          stan::model::assign(tau2, tau2_flat__[(pos__ - 1)],
            "assigning variable tau2", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, tau2);
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 4;
      alpha = context__.vals_r("alpha")[(1 - 1)];
      out__.write_free_lb(0, alpha);
      local_scalar_t__ gamma = DUMMY_VAR__;
      current_statement__ = 5;
      gamma = context__.vals_r("gamma")[(1 - 1)];
      out__.write_free_lb(0, gamma);
      Eigen::Matrix<local_scalar_t__,-1,1> nu =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> nu_flat__;
        current_statement__ = 6;
        nu_flat__ = context__.vals_r("nu");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          stan::model::assign(nu, nu_flat__[(pos__ - 1)],
            "assigning variable nu", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(nu);
      Eigen::Matrix<local_scalar_t__,-1,1> lambda =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(D, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> lambda_flat__;
        current_statement__ = 7;
        lambda_flat__ = context__.vals_r("lambda");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          stan::model::assign(lambda, lambda_flat__[(pos__ - 1)],
            "assigning variable lambda", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, lambda);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"sig2", "Beta", "tau2", "alpha",
                "gamma", "nu", "lambda"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"all_sig2", "all_mu"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(B)},
                std::vector<size_t>{static_cast<size_t>(B),
                  static_cast<size_t>(D)},
                std::vector<size_t>{static_cast<size_t>(D)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{static_cast<size_t>(D)},
                std::vector<size_t>{static_cast<size_t>(D)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)},
             std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= B; ++sym1__) {
      param_names__.emplace_back(std::string() + "sig2" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= B; ++sym2__) {
        param_names__.emplace_back(std::string() + "Beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      param_names__.emplace_back(std::string() + "tau2" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "gamma");
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "all_sig2" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "all_mu" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= B; ++sym1__) {
      param_names__.emplace_back(std::string() + "sig2" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= B; ++sym2__) {
        param_names__.emplace_back(std::string() + "Beta" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      param_names__.emplace_back(std::string() + "tau2" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "gamma");
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      param_names__.emplace_back(std::string() + "nu" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
      param_names__.emplace_back(std::string() + "lambda" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "all_sig2" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "all_mu" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"sig2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(B) + "},\"block\":\"parameters\"},{\"name\":\"Beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(B) + ",\"cols\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"tau2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"all_sig2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"all_mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"sig2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(B) + "},\"block\":\"parameters\"},{\"name\":\"Beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(B) + ",\"cols\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"tau2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"gamma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"lambda\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(D) + "},\"block\":\"parameters\"},{\"name\":\"all_sig2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"all_mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((B + (B * D)) + D) + 1) + 1) + D) + D);
    const size_t num_transformed = emit_transformed_parameters * ((N + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((((B + (B * D)) + D) + 1) + 1) + D) + D);
    const size_t num_transformed = emit_transformed_parameters * ((N + N));
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = conjugate_model_model_namespace::conjugate_model_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return conjugate_model_model_namespace::profiles__;
}
#endif